#!/usr/bin/env bun
import { writeFileSync } from "node:fs";
import { visitorKeys } from "@typescript-eslint/visitor-keys";

writeFileSync(
  "./src/visitor-keys.ts",
  `// This file is generated by scripts/generate-visitor-keys.ts
// prettier-ignore
export const visitorKeys: Record<string, string[] | undefined> = {${Object.entries(
    visitorKeys,
  )
    .filter(([, v]) => v?.length)
    .map(([k, v]) => `\n  ${k}: [${v!.map((v) => `"${v}"`).join(", ")}],`)
    .join("")}
};
`,
);
